export const RESEND_PAGE_SIZE = 100;

export const TWENTY_PAGE_SIZE = 100;

export const RATE_LIMIT_MAX_RETRIES = 5;

export const RATE_LIMIT_BASE_DELAY_MS = 1000;

export const RATE_LIMIT_MIN_INTERVAL_MS = 220;

export const SYNC_LOOKUP_PROGRESS = 0.1;

export const DETAILS_FETCH_BATCH_SIZE = 50;

export const DETAILS_FETCH_HARD_CAP = 1000;

export const DETAILS_FETCH_SOFT_DEADLINE_MS = 270_000;

export const DETAILS_FETCH_MAX_RETRIES = 5;

export const INITIAL_SYNC_MODE_ENV_VAR_NAME = 'INITIAL_SYNC_MODE';

export const INTERMEDIATE_SYNC_EMAILS_MAX_AGE_MS = 7 * 24 * 60 * 60 * 1000;
